baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Faiz Halde'
subtitle = 'takeaways'
theme = 'yinyang'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'vim'
    tabWidth = 4

[author]
  name = "Faiz Halde"
  homepage = "https://joway.io/"

[params]
headTitle = "Faiz Halde"
Description = 'Takeaways'
mainSections = ["posts"]
[[params.socials]]
name = "METADATA"
link = "/posts/metadata"
[[params.socials]]
name = "GITHUB"
link = "https://github.com/fhalde"
